import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../app/components/Header"
import Introduction from "./components/Introduction"
import { Inter } from 'next/font/google'
import Skills from "./components/Skills"
import Experience from "./components/Experience";
import {About} from "./components/About";
import Projects from "./components/Projects";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div>
      <body>
        <Header/>
        <Introduction/>
        <Skills/>
        <Experience/>
        <About/>
        <Projects/> 
        {children}
      </body>
      </div>
  
    </html>
  );
}
